### PR TITLE
Added Player.fm support

### PR DESCRIPTION
**Pull request by TheQuietCroc**

### CODE REVIEW

**Comment by tjhrulz** [comment]
Code seems fine to me, given this is a site I do not use I can not test it but what you have here seems fine. Going to merge into master

**Comment by TheQuietCroc** [comment]
I noticed that the Firefox version was updated to 0.4.8 but the Chrome version is still stuck on 0.4.7. About how long does it take for the Chrome version to be updated in the store?

**Comment by tjhrulz** [comment]
Well usually a day, but this is my first post COVID release and well it seems Google is taking their sweet time with the review. I am not too far from pestering their support team since it has been now a week since I uploaded it and Firefox completed their in depth review within a few hours. Pre-COVID usually Chrome was faster than Firefox for approving my extension updates.

I understand why it is a longer process as Chrome has been trying to cut down on programs that do things like say inject ads into a page so anything that uses host permissions and thus gets access to page it does not make goes through a manual review process.

The worst part with Chrome though is you just get left in limbo, at least Firefox tells you where you are at in their queue. Also Chrome does not let me upload another version while it is under review so I may just end up pushing another update to Firefox before Chrome even gets this one.

**Comment by TheQuietCroc** [comment]
Dude, that sucks. I figured it was something like that though.

**Comment by tjhrulz** [comment]
Yeah I reached out to the Chrome support team and I guess we will see what they say. I reached out though not because I want to get bumped ahead in the queue but because I just feel the process is not handled as well on the Chrome web store as it is on the Firefox store. I doubt anything comes of it but I just feel that the experience for devs and users could be handled better.

If anyone would like to know what I said I pasted it below. 
Note: they limited me to 1500 chars so I had to keep it pretty brief
> I want to start by saying understand that the manual review process is taking longer post COVID, I also understand that this is the first update for this extension for a while which even further encourages a thorough manual review, and I also understand that Chrome and other browsers have been trying to do a better job of finding extension that take advantage of host permissions to track users or inject ads during the review process.
> 
> However it has been a week since I uploaded my update, the Firefox web store completed its manual review within a day. I don't mind that the process takes time however the lack of any idea of where the process is at is frustrating. This update is mainly bug fixes and asks for no new permissions, I have a community asking me why the Chrome version is not up to date like the other versions are. This also is preventing me from releasing further updates I have ready since I can't even upload a newer version of the extension to be reviewed (I kind of understand this but there are ways you should be able to handle that).
> 
> All I am asking for is not to get bumped ahead of other extensions in the queue, I just feel that devs deserve better transparency (like showing where one is at in the queue like the or an estimate of how long the process will take), or a better experience during the manual review process, or giving users an option to manually update to versions still in review would be very helpful. Your competition does some of this and you should to.
```

**Comment by tjhrulz** [comment]
Wow I actually got a response, and within 4 hours, impressive. However the response seems to just be a copy paste response (It may have been fully automated but given it has a person name attached to it and it was roughly on topic I think it was just a generic). 

Basically the response says our request has been escalated and reminded me that extensions may be flagged for manual review and that this process takes time and I can not modify/update my item or cancel the review while it is in progress. It also reminded me that the can very in length of time and that due to COVID their may be limitations and delays in support.

I find this pretty funny because their email basically says everything I already said in my request and they said they would do the one thing I said I didn't need them to do (Jump me ahead in the queue) as their solution to the problem.

**Comment by TheQuietCroc** [comment]
Sounds automated as hell tbh lol. Well at least we know it's a fault on their end.

**Comment by tjhrulz** [comment]
Well it only took almost two weeks but chrome has pushed the update it would seem, I guess time to wrap up the next update and submit it

**Comment by TheQuietCroc** [comment]
Excellent, good luck with the next update!

**Pull request merged**
